#!/usr/bin/env python

# RNA Transcription
# =================
# 
# An RNA string is formed from the alphabet containing A, C, G, and U.
# 
# Given a DNA string t corresponding to a coding strand, its transcribed RNA 
# string u is formed by replacing all occurrences of T with U.
# 
# Given: A DNA string t of length at most 1000 nucleotides.
# 
# Return: The transcribed RNA string of t.
# 
# Sample Dataset
# --------------
# GATGGAACTTGACTACGTAAATT
# 
# Sample Output
# -------------
# GAUGGAACUUGACUACGUAAAUU


def transcribe_rna(t):
    return t.replace('T','U')


if __name__ == "__main__":

    small_dataset = "GATGGAACTTGACTACGTAAATT"
    large_dataset = "GAACTAAGGGCTGGGTTATGCTCCCTAGTTCCAACCTGCGGCTAAGAATCATTAGGTAGATAGTGCGGTAAGGGTGTAACATTACCGCCTTTAATCTTCTCTCCGTAGGGTTAAGGCTGGGTTAAGAGTACGACTATGATCCAGGGCGACTGATGGGTGTTTCGGGGACGCCCTGTTGAGCAAGGCTGAATTAATGCGAGTGTAACTTAGTATGTCGCAACTCGCTGTGCCATCCGTAAGGCGTTACGCACAGGTTATGCATCTTGCACGGCCTCTATGGAGAGACTTGTCACGTTATTTATGACAACACTGGGGCAGATATACCCTCACCGAGTGCCCGCCCTGTTCACTACAACCATCGACGCGATCTCGAACTTGATACTAACTCTGGGCGACGTACAAGGTCGGGGTCACACCGCCCGGGGCATACATTAGTGAGAGCTAACCCACATATTTCATTGGTGTCCCGATACTCCGCCGCTATTATGTATAATTTGTCACACCGCTGGCCTAGACCACACCACACACTGACTTAATGCTTGCACCTCTCCTAAAACAAGTGCACATGAGGGTAATATCGCGACTTTCTTCATGAACATCATCGATGTCACATCTCAATAGTGCTTCTGAATCGCTAGCCTCTGGTCGGAGGATACTGATAAGGCGCTTAACCAAGGCATTCAGTGAGTTAGCGGGTCGTCTTGCGCGCCAATCCCTTACAAATTTTTCTGGCTTAGCCCTGAAGCCTTCTCTACATATAGGGGTATGTGAGTCGCAGGTAAGCCTTCTTCTAGGGTAAGGTCAGACAATCTGTGTATTATATCGTAAGGTAGGCAAGCCCGTTGCTTCGTGCCTTTATCATTGACATATTCAAAATTGGCGGGACTCAAGCTTGCGTGGAC"

    print transcribe_rna(large_dataset)

